from pdf_extractor import *

global_text = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc blandit lorem ex, sit amet iaculis purus porta nec. Aenean vitae ex sed elit pellentesque elementum et rhoncus neque. Phasellus hendrerit non urna vitae efficitur. Sed at augue ac diam venenatis lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam eget nunc nec tellus eleifend finibus. Pellentesque eu ligula congue, bibendum justo ac, bibendum tellus. Donec vel pharetra ligula, sed finibus nulla. Ut sed ligula laoreet augue euismod tristique.
Donec vitae justo id elit pulvinar faucibus. Suspendisse condimentum tristique pretium. Nunc nec aliquet arcu. Nulla auctor lacus quis erat viverra lacinia eget vitae ex. Phasellus id nunc nisl. Donec maximus posuere diam in rutrum. Cras dignissim risus ut neque varius, et ultricies elit hendrerit. Etiam quis auctor massa. Sed ac nunc tempus, elementum erat eu, accumsan tellus. Donec blandit risus libero, a dignissim enim gravida et. Nam rutrum vitae augue eu congue. Fusce rutrum diam ac augue dictum ultricies eget eget nibh. Praesent vulputate enim eget sapien sollicitudin, quis bibendum diam blandit.
Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam leo erat, sollicitudin a ultricies vitae, facilisis eget lectus. Sed neque diam, ultricies eu tortor congue, efficitur mollis massa. Nullam luctus vel mi et aliquet. Maecenas scelerisque diam nunc, at vestibulum elit ornare non. Morbi cursus vehicula lorem, eu volutpat enim pharetra at. Aliquam ligula neque, ultricies mollis arcu a, faucibus laoreet urna. Cras ornare, nisi ut varius aliquam, nibh orci condimentum eros, eget efficitur massa nulla vel dui. Nunc eget tortor et est bibendum fermentum. Mauris tincidunt mattis vehicula.
Donec sit amet orci nisi. Mauris blandit nibh non rhoncus pretium. Vivamus erat odio, efficitur sed nisi ultrices, tincidunt consequat leo. Cras convallis, velit eu fringilla pharetra, tortor nisl tincidunt purus, et lacinia odio metus eget libero. Phasellus ornare mollis neque vel dapibus. Vestibulum at molestie enim, a rhoncus mi. Curabitur quis velit erat. In mauris nunc, venenatis at bibendum id, pharetra eu metus. Duis pharetra, ante non ultricies sodales, leo tellus laoreet dui, at interdum ex leo a leo. In eu urna laoreet, euismod nisi sit amet, luctus risus. Donec pellentesque massa metus, eu interdum lectus aliquet quis. In at posuere libero, ut varius urna. Mauris mollis pretium ipsum vitae convallis.
Fusce iaculis non turpis et semper. Suspendisse non nisl ut tortor gravida dignissim. Quisque eget maximus felis. Integer feugiat, ex eu consequat lacinia, purus lectus placerat ante, sed egestas mi turpis ac diam. Sed ex sem, porttitor vel velit sit amet, rutrum ultrices nulla. Curabitur pellentesque nunc faucibus enim gravida euismod. Duis a ex non tortor dictum placerat molestie in velit. Suspendisse volutpat scelerisque nunc vitae fringilla. Donec ornare vestibulum feugiat. Vivamus rhoncus arcu id maximus gravida. Etiam mollis, turpis id fermentum tincidunt, massa diam feugiat velit, non pharetra ante metus at dui. Phasellus quis gravida magna.
"""


def test_retourne_un_pdf():
    pdf_path = "ressources/La première loi de Newton.pdf"
    assert len(read_pdf(pdf_path).pages) == 1


def test_doit_retourner_un_titre_sans_caractere_speciaux():
    texte = "Ceci est un exemple de texte avec des espaces"
    assert rename(texte) == "Ceci_est_un_exemple_de_texte_avec_des_espaces"


def test_recupere_la_liste_des_paragraphes_ayant_un_mot_clef():
    liste_de_paragraphes: list[str] = global_text.split("\n")
    mot_clef: str = "consectetur"
    expected: list[str] = ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc blandit lorem ex, sit amet iaculis purus porta nec. Aenean vitae ex sed elit pellentesque elementum et rhoncus neque. Phasellus hendrerit non urna vitae efficitur. Sed at augue ac diam venenatis lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam eget nunc nec tellus eleifend finibus. Pellentesque eu ligula congue, bibendum justo ac, bibendum tellus. Donec vel pharetra ligula, sed finibus nulla. Ut sed ligula laoreet augue euismod tristique.\nDonec vitae justo id elit pulvinar faucibus. Suspendisse condimentum tristique pretium. Nunc nec aliquet arcu. Nulla auctor lacus quis erat viverra lacinia eget vitae ex. Phasellus id nunc nisl. Donec maximus posuere diam in rutrum. Cras dignissim risus ut neque varius, et ultricies elit hendrerit. Etiam quis auctor massa. Sed ac nunc tempus, elementum erat eu, accumsan tellus. Donec blandit risus libero, a dignissim enim gravida et. Nam rutrum vitae augue eu congue. Fusce rutrum diam ac augue dictum ultricies eget eget nibh. Praesent vulputate enim eget sapien sollicitudin, quis bibendum diam blandit.\nOrci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam leo erat, sollicitudin a ultricies vitae, facilisis eget lectus. Sed neque diam, ultricies eu tortor congue, efficitur mollis massa. Nullam luctus vel mi et aliquet. Maecenas scelerisque diam nunc, at vestibulum elit ornare non. Morbi cursus vehicula lorem, eu volutpat enim pharetra at. Aliquam ligula neque, ultricies mollis arcu a, faucibus laoreet urna. Cras ornare, nisi ut varius aliquam, nibh orci condimentum eros, eget efficitur massa nulla vel dui. Nunc eget tortor et est bibendum fermentum. Mauris tincidunt mattis vehicula."]
    assert get_list_of_paragraph_with_keywords(liste_de_paragraphes, mot_clef) == expected
